# Copyright 2022 The MathWorks, Inc.
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.taskUID }}
  labels:
      jobUID: {{ .Values.jobUID }}
      taskUID: {{ .Values.taskUID }}
spec:
  backoffLimit: 0
  {{- if (.Values.automaticJobCleanup | default false) }}
  ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished }}
  {{- end }}
  template:
    metadata:
      name: secondary-communicating-matlab-job-pod
      labels:
        jobUID: {{ .Values.jobUID }}
        taskUID: {{ .Values.taskUID }}
    spec:
      restartPolicy: Never
      containers:
      - name: secondary-communicating-matlab-job
        image: {{ .Values.image | quote }}
        imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
        args:
        - /scripts/secondaryWorker.sh
        resources:
          requests:
            cpu: {{ .Values.numThreads }}

        # Set locations in the container of directories mounted from cluster -> container
        volumeMounts:
        - name: data-volume
          mountPath: {{ .Values.containerJobStorageLocation }}
        - name: secret-volume
          mountPath: /ssh-keys
          readOnly: true
        {{ if .Values.mountMatlab }}
        - name: matlab-volume
          mountPath: {{ .Values.containerMatlabRoot }}
          readOnly: true
        {{ end }}

        env:
        - name: PARALLEL_SERVER_DECODE_FUNCTION
          value: {{ .Values.parallelServer.decodeFunction | quote }}
        - name: PARALLEL_SERVER_STORAGE_CONSTRUCTOR
          value: {{ .Values.parallelServer.storageConstructor | quote }}
        - name: PARALLEL_SERVER_STORAGE_LOCATION
          value: {{ .Values.containerJobStorageLocation }}
        - name: PARALLEL_SERVER_JOB_LOCATION
          value: {{ .Values.parallelServer.jobLocation | quote }}
        - name: PARALLEL_SERVER_MATLAB_ARGS
          value: {{ .Values.parallelServer.matlabArgs | quote }}
        - name: PARALLEL_SERVER_USER_ID
          value: {{ .Values.parallelServer.userID | quote }}
        - name: PARALLEL_SERVER_GROUP_ID
          value: {{ .Values.parallelServer.groupID | quote }}
        - name: PARALLEL_SERVER_DEBUG
          value: {{ .Values.parallelServer.debug | default 0 | quote }}
        - name: PARALLEL_SERVER_USERNAME
          value: {{ .Values.username }}
        - name: LOGFILE
          value: {{ .Values.logfile }}

      # Set locations on the cluster of directories mounted from cluster -> container
      volumes:
      - name: data-volume
        {{- if $.Values.jobStorageServer }}
        nfs:
          server: {{ $.Values.jobStorageServer }}
        {{- else }}
        hostPath:
          type: Directory
        {{- end }}
          path: {{ $.Values.clusterJobStorageLocation | quote }}

      {{- if $.Values.mountMatlab }}
      - name: matlab-volume
        {{- if $.Values.matlabServer }}
        nfs:
          server: {{ $.Values.matlabServer }}
        {{- else }}
        hostPath:
          type: Directory
        {{- end }}
          path: {{ $.Values.clusterMatlabRoot | quote }}
      {{- end }}

      - name: secret-volume
        secret:
          secretName: {{ .Values.secretName | quote }}

      hostAliases:
      - ip: {{ .Values.hostIP | quote }}
        hostnames:
        - {{ .Values.hostname | quote }}
