# Copyright 2022 The MathWorks, Inc.
apiVersion: v1
kind: ServiceAccount
metadata:
    name: {{ .Values.serviceAccountName }}
---
{{ $roleName := (printf "%s-%s-%s-role" .Values.username .Values.parallelServer.jobLocation .Values.jobUID) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $roleName }}
rules:
  - apiGroups: [""]
    resources:
      - pods
      - secrets
    verbs:
      - get
      - list
      - create
      - delete
      - update
  - apiGroups: ["batch"]
    resources:
      - jobs
    verbs:
      - get
      - list
      - create
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "%s-%s-%s-role-binding" .Values.username .Values.parallelServer.jobLocation .Values.jobUID }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccountName }}
roleRef:
  kind: Role
  name: {{ $roleName }}
  apiGroup: rbac.authorization.k8s.io
